codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 70%
        threshold: 1%
        if_ci_failed: error
    
    patch:
      default:
        target: 70%
        threshold: 5%
        if_ci_failed: error

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "tests/**/*"
  - "benches/**/*"
  - "examples/**/*"

flags:
  unit:
    paths:
      - src/
    carryforward: true
  
  integration:
    paths:
      - src/
    carryforward: true
